# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  testing:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    docker:
      - image: cimg/node:16.17.0-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      # look for existing cache and restore if found
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      # install dependencies
      - run:
          name: Install dependencies
          command: npm install
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      # run test suite
      - run:
          name: Testing
          command: npm run test

workflows:
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  do_testing:
    jobs:
      - testing:
          filters:
            branches:
              only:
                - main

